### ISSUE TITLE
log_f0 does n't exist

### ISSUE THREAD

**Issue by abuvaneswari** [jjery2243542/voice_conversion#5]
Hello,

I was able to run make_dataset_vctk.py and get a h5py output. But the mcep normalize fails:
python mcep_normalize.py VCTK_h5py VCTK_h5py_norm
processing speaker_id=225
Traceback (most recent call last):
  File "mcep_normalize.py", line 13, in <module>
    utt_f0 = [f_in[f'train/{speaker}/{utt_id}/log_f0'][()] for utt_id in f_in[f'train/{speaker}'].keys()]
  File "mcep_normalize.py", line 13, in <listcomp>
    utt_f0 = [f_in[f'train/{speaker}/{utt_id}/log_f0'][()] for utt_id in f_in[f'train/{speaker}'].keys()]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/tfs/venv_voice_conversion_jjerry/lib/python3.6/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'log_f0' doesn't exist)"

Apparently, you are saving mel and lin in the make_dataset*.py modules. but you are reading log_f0, mc_mean, mc_std, f0_mean, f0_std in your mcep_normalize as well as your convert.py codes. 

Is your documentation missing a step that arrives at log_f0, mc_mean, mc_std, f0_mean, f0_std ?

Please clarify

Thanks,
Buvana

**Comment by jjery2243542** [comment]
Hi, 
I used log-power spectrum instead. The mc, f0 doesn't work.
